#!/bin/bash

# Verifica se o dispositivo padrão de áudio é a placa de som do notebook
if ! amixer sget Master | grep -q "Simple mixer control 'Master',"; then
    echo "Placa de som não encontrada."
    exit 1
fi

# Verifica se o som já está mutado
if amixer sget Master | grep -q "\[off\]"; then
    amixer -q set Master unmute # Desmuta o som
    echo "Som ligado."
else
    amixer -q set Master mute # Muta o som
    echo "Som desligado."
fi
