#!/usr/bin/env bash

touchpad_id=$(xinput list | grep -i touchpad | awk -F= '{print $2}' | cut -f1)

if [ $(xinput list-props "$touchpad_id" | grep "Device Enabled" | awk '{print $NF}') -eq 1 ]; then
    echo "Switching off"
    xinput disable "$touchpad_id"
else
    echo "Switching on"
    xinput enable "$touchpad_id"
fi
