#!/bin/bash

USER="sevle"
PUBLIC="/home/$USER/público"
PROJECT="/home/$USER/projetos/virtual-machines/"

echo "2 para windows, 1 para gentoo"
read CHOOSE

if [ $CHOOSE -eq 1 ]; then
    OS="$PROJECT/gentoo-virtual/"

elif [ $CHOOSE -eq 2 ]; then
    OS="$PROJECT/windows-virtual/"

else 
    echo "td errado, olha so q disgraça"
fi    

ISO=$(find $OS -type f -name "*.iso")
DISK_IMAGE=$(find $OS -type f -name "*.qcow2")

qemu-system-x86_64 \
    -runas $USER \
    -smp $(nproc) \
    -cpu host \
    -m 2G \
    -boot d \
    -cdrom $ISO \
    -rtc base=localtime \
    -drive file="$DISK_IMAGE",cache=writeback \
    -drive file="fat:rw:$PUBLIC",format=raw \
    -device intel-hda \
    -device hda-duplex \
    -device virtio-net-pci,netdev=net0,mac=52:54:00:12:34:56 \
    -netdev bridge,id=net0,br=br0 \
    -enable-kvm \
