#!/bin/sh

USER="sevle"
PUBLIC="/home/$USER/público"
WINDOWS_PROJECT="/home/$USER/projetos/windows-virtual"

WINDOWS_ISO="$WINDOWS_PROJECT/WindowsOS.iso"
DISK_IMAGE="$WINDOWS_PROJECT/disk.qcow2"

qemu-system-x86_64 \
    -runas $USER \
    -smp $(nproc) \
    -cpu host \
    -m 2G \
    -boot d \
    -cdrom $WINDOWS_ISO \
    -rtc base=localtime \
    -drive file="$DISK_IMAGE",cache=writeback \
    -drive file="fat:rw:$PUBLIC",format=raw \
    -device intel-hda \
    -device hda-duplex \
    -device virtio-net-pci,netdev=net0,mac=52:54:00:12:34:56 \
    -netdev bridge,id=net0,br=br0 \
    -enable-kvm \
