#!/bin/bash

user="sevle"
public="/home/$user/público"
project="/home/$user/projetos/virtual-machines/"
os="$project/artix-virtual/"
disk_image=$(find $os -type f -name "*.qcow2")
    
qemu-system-x86_64 -m 2048 -boot c -hda $disk_image
