#!/bin/bash

# define os mapeamentos do nnn para o vim
nnn_bindings="\
map h         ^ \
map j         +down \
map k         +up \
map l         $ \
map gg        g \
map G         G \
map dd        _delete \
map y         +copy \
map p         +paste \
map P         _rename \
map /         /_search \
map n         n \
map N         N \
map :         :_shell \
map q         :q! \
map Q         :q! \
map R         _redraw \
map o         _mkdir \
map O         _create \
map t         _touch \
map m         _archive \
map `         _cd \
map ~         _cd ~ \
map -         _cd - \
map b         _bookmarks \
map c         _copy \
map d         _delete \
map e         _edit \
map f         _find \
map F         _find -iname \
map j         +down \
map k         +up \
map h         +left \
map l         +right \
map m         _mark \
map n         _next \
map N         _prev \
map p         +paste \
map r         _rename \
map s         _stat \
map t         _touch \
map y         +copy \
map z         _compress \
map Z         _decompress \
map =         _du \
map \         _cd -
"

# define o comando de execução do nnn
nnn_cmd="nnn"

# define o nome do arquivo temporário que armazenará os mapeamentos do nnn
nnn_mappings_file="/tmp/nnn_mappings"

# salva os mapeamentos personalizados em um arquivo temporário
echo "${nnn_bindings}" > "${nnn_mappings_file}"

# executa o nnn com os mapeamentos personalizados
$nnn_cmd -p "`cat ${nnn_mappings_file}`"

# remove o arquivo temporário
rm "${nnn_mappings_file}"
